### PR TITLE
update header footer based on mockups

### PR DESCRIPTION
**Pull request by itzsaga**

### CODE REVIEW

**Comment by itzsaga** [comment]
screenshot

Footer isn't sticky. Not blocking but would be nice.

<details><summary>Browser metadata</summary>





```
Path:      /about/
Browser:   Firefox 113.0 on Mac OS 10.15
Viewport:  1280 x 1330 @2x
Language:  en-US
Cookies:   Enabled
```

[Open in BrowserStack](https://www.browserstack.com/user/try-live?url=https%3A%2F%2Fdeploy-preview-2--undergroundjs-2023.netlify.app%2Fabout%2F&os=OS%20X&os_version=Catalina&browser=Firefox&browser_version=113.0&resolution=1280x1330&speed=1&start=true&ref=netlify-source)



</details>

[Open Deploy Preview](https://deploy-preview-2--undergroundjs-2023.netlify.app/about/) · [Mark as Resolved](https://app.netlify.com/cdp/resolve?deployID=643813a621aa130008f1434b&commentID=643814f533e78303246b04f9&resolution=resolved)

**Comment by kwelch** [comment]
@itzsaga for the footer, honestly, I would just put the page background to black and it will make it look like it is all the way down.

**Comment by itzsaga** [comment]
> @itzsaga for the footer, honestly, I would just put the page background to black and it will make it look like it is all the way down.

I only call it out because on the home page it's pushed to the bottom. Inconsistent, probably some code to call out but haven't looked at it just yet.

**Comment by kwelch** [comment]
Yea, it is an easy fix. I would just `body {background: "#000"}` and then in `main`, we add a `#FFF` background and pay with the width. I tested this out in browser dev-tools.

**Pull request merged**
